### ISSUE TITLE
emacs-27 can not work

### ISSUE THREAD

**Issue by e190** [honmaple/emacs-maple-imenu#1]
在 windos 的 emacs-27.不能成功使用。
报错：
no imenu found

**Comment by honmaple** [comment]
这不是报错，而是没有imenu列表，你可以试试`(imenu--make-index-alist t)`或者`(counsel-imenu)`看是否有值显示

**Comment by e190** [comment]
> 
> 
> 这不是报错，而是没有imenu列表，你可以试试`(imenu--make-index-alist t)`或者`(counsel-imenu)`看是否有值显示

这两个都不能显示，但是 imenu-list 可以显示

**Comment by honmaple** [comment]
查看`imenu-create-index-function`的值，imenu-list可能单独或者临时设置了`imenu-create-index-function`

**Comment by e190** [comment]
![图片](https://user-images.githubusercontent.com/39932163/68361944-8cdcf300-0160-11ea-9daa-fa91df030ebc.png)
感觉看不出什么来。
但是在imenu-list的源码里面有这样的函数：
![图片](https://user-images.githubusercontent.com/39932163/68362013-beee5500-0160-11ea-8580-34de8aad9b8a.png)
