### ISSUE TITLE
maple-imenu-autoresize 显示不完整

### ISSUE THREAD

**Issue by e190** [honmaple/emacs-maple-imenu#2]
开启 maple-imenu-autoresize 后，最长的那个条目 仍然 显示不完整。
![图片](https://user-images.githubusercontent.com/39932163/209607983-dce33a0c-4dff-4860-953a-98b3d1949437.png)

我觉得应该是 Variables Functions 标题前面有个三角符号，导致窗口计算不对。

```
(defun maple-imenu-refresh()
  "Refresh imenu buffer."
  (interactive)
  (maple-imenu--with-writable
    (erase-buffer)
    (dolist (item (maple-imenu--entries))
      (maple-imenu--handler item)))
  (when maple-imenu-autoresize
    (maple-imenu--with-window
      (let ((fit-window-to-buffer-horizontally t))
        (fit-window-to-buffer)))))
```
我想在 maple-imenu-autoresize 的基础上 多增加两个字符的宽度，就没问题了。
不知道 怎么来做这个功能

**Comment by honmaple** [comment]
现在适应窗口大小是用的内置函数`fit-window-to-buffer`, 如果想要真正完全适应，必须逐行统计并计算buffer内的最大长度，还有一种方式是可以使用两次`fit-window-to-buffer`
```
(when maple-imenu-autoresize
    (maple-imenu--with-window
      (let ((fit-window-to-buffer-horizontally t))
        (fit-window-to-buffer)
        (fit-window-to-buffer nil nil nil nil (+ (window-width) 5))
        )))
```
或者打开自动换行`toggle-truncate-lines`, 不过我觉得太长的函数名是没必要显示完整的，会影响正文显示
